# Cargo.toml
[workspace]
members = [ "collection", "custom_types", "first_lib", "hash_map",
    "hello_world", "packaging", "primitive", "types", "youtube_temp",
]
resolver = "2" # or "1", depending on your preference

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true    # Enable Link Time Optimization
